base_url: "https://whatsapp.turn.io"
# Prod has different URL
# base_url: "https://whatsapp.who.turn.io"
urls:
  - name: contentrepo
    qa_url: "https://content-repo-api-qa.prk-k8s.prd-p6t.org"
    prod_url: "https://platform-mnch-contentrepo.prk-k8s.prd-p6t.org"
stack_uuids:
  - name: DMA Form
    qa_uuid: 690a9ffd-db6d-42df-ad8f-a1e5b469a099
    prod_uuid: b283e7c1-0a79-45ab-976c-5566d9ba06cd